Edit build script 4

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,13 +1,22 @@
 #!/bin/bash
 
-printf "\n>> (1/2) Change working directory to 'src/Go/hotelbooking'...\n\n"
+printf "\n>> (1/3) Change working directory to 'src/Go/hotelbooking'...\n\n"
 cd src/Go/hotelbooking
 
-printf "\n>> (2/2) Building REST API executable...\n\n"
+printf "\n>> (2/3) Copying 'config.json'...\n\n"
+cp ~/config/config.json .
+
+if [[ $? -ne 0 ]]
+then
+    printf "\n\n(!) Copy failed.\n\n"
+    exit 1
+fi
+
+printf "\n>> (3/3) Building REST API executable...\n\n"
 /usr/local/go/bin/go build
 
 if [[ $? -ne 0 ]]
 then
     printf "\n\n(!) Build failed.\n\n"
-    exit 1
+    exit 2
 fi
